Debug hdf5

diff --git a/.github/workflows/macos_intel.yml b/.github/workflows/macos_intel.yml
--- a/.github/workflows/macos_intel.yml
+++ b/.github/workflows/macos_intel.yml
@@ -102,81 +102,83 @@ jobs:
           export CC=mpicc
           export FC=mpif90
           export CXX=mpicxx
-          cat ${HOME}/openmpi/bin/mpicc
-          wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz &> /dev/null
-          tar -xzf hdf5-1.10.7.tar.gz
-          pushd hdf5-1.10.7
-          ./configure --prefix=${HOME}/netcdf --enable-parallel --disable-tools --disable-fortran --disable-cxx --enable-parallel-tests
-          make -j2 VERBOSE=1
-          make install
-
-      # Build NetCDF-C   
-      - name: Build NetCDF-C
-        if: steps.cache-netcdf.outputs.cache-hit != 'true'
-        run: |
-          source /opt/intel/oneapi/setvars.sh
-          export PATH="${HOME}/openmpi/bin:$PATH"
-          export CC=mpicc
-          export CPPFLAGS=-I${HOME}/netcdf/include
-          export LDFLAGS=-L${HOME}/netcdf/lib
-          wget https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.4.tar.gz &> /dev/null
-          tar -xzf netcdf-c-4.7.4.tar.gz
-          pushd netcdf-c-4.7.4
-          ./configure --prefix=${HOME}/netcdf --disable-dap --disable-utilities
-          make -j2
-          make install
-
-      # Build NetCDF-Fortran
-      - name: Build NetCDF-Fortran
-        if: steps.cache-netcdf.outputs.cache-hit != 'true'
-        run: |
-          source /opt/intel/oneapi/setvars.sh
-          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${HOME}/netcdf/lib"
-          export PATH="${HOME}/netcdf/bin:$PATH"
-          export PATH="${HOME}/openmpi/bin:$PATH"
-          export CC=mpicc
-          export FC=mpif90
-          export CPPFLAGS=-I${HOME}/netcdf/include
-          export LDFLAGS=-L${HOME}/netcdf/lib
-          wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
-          tar -xzf v4.5.3.tar.gz
-          pushd netcdf-fortran-4.5.3
-          ./configure --prefix=${HOME}/netcdf
-          make -j2
-          make install
-
-      # Get NetCDF versions
-      - name: Get NetCDF version
-        run: |
-          export PATH="${HOME}/netcdf/bin:$PATH"
-          nc-config --version
-          nf-config --version
-
-      # Test debug mode
-      - name: Test Shallow Water Debug
-        run: |
-          source /opt/intel/oneapi/setvars.sh
-          export PATH="${HOME}/openmpi/bin:$PATH"
           ldd ${HOME}/openmpi/bin/mpicc
-          ldd ${HOME}/openmpi/bin/mpif90
-          ldd ${HOME}/netcdf/lib/libnetcdf
-          cd build
-          rm -rf *
-          export CC=icc
-          export FC=ifort
-          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_PREFIX_PATH='~;~/netcdf;~/openmpi' ..
-          make VERBOSE=1
-          ctest --output-on-failure
+#          wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz &> /dev/null
+#          tar -xzf hdf5-1.10.7.tar.gz
+#          pushd hdf5-1.10.7
+#          ./configure --prefix=${HOME}/netcdf --enable-parallel --disable-tools --disable-fortran --disable-cxx --enable-parallel-tests
+#          make -j2 VERBOSE=1
+#          make install
+          ls -l ${HOME}/netcdf/lib
+          exit 1
 
-      # Test release mode
-      - name: Test Shallow Water Release
-        run: |
-          source /opt/intel/oneapi/setvars.sh
-          export PATH="${HOME}/openmpi/bin:$PATH"
-          cd build
-          rm -rf *
-          export CC=mpicc
-          export FC=mpif90
-          cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_PREFIX_PATH='~;~/netcdf;~/openmpi' ..
-          make VERBOSE=1
-          ctest --output-on-failure
+#      # Build NetCDF-C   
+#      - name: Build NetCDF-C
+#        if: steps.cache-netcdf.outputs.cache-hit != 'true'
+#        run: |
+#          source /opt/intel/oneapi/setvars.sh
+#          export PATH="${HOME}/openmpi/bin:$PATH"
+#          export CC=mpicc
+#          export CPPFLAGS=-I${HOME}/netcdf/include
+#          export LDFLAGS=-L${HOME}/netcdf/lib
+#          wget https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.4.tar.gz &> /dev/null
+#          tar -xzf netcdf-c-4.7.4.tar.gz
+#          pushd netcdf-c-4.7.4
+#          ./configure --prefix=${HOME}/netcdf --disable-dap --disable-utilities
+#          make -j2
+#          make install
+#
+#      # Build NetCDF-Fortran
+#      - name: Build NetCDF-Fortran
+#        if: steps.cache-netcdf.outputs.cache-hit != 'true'
+#        run: |
+#          source /opt/intel/oneapi/setvars.sh
+#          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${HOME}/netcdf/lib"
+#          export PATH="${HOME}/netcdf/bin:$PATH"
+#          export PATH="${HOME}/openmpi/bin:$PATH"
+#          export CC=mpicc
+#          export FC=mpif90
+#          export CPPFLAGS=-I${HOME}/netcdf/include
+#          export LDFLAGS=-L${HOME}/netcdf/lib
+#          wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
+#          tar -xzf v4.5.3.tar.gz
+#          pushd netcdf-fortran-4.5.3
+#          ./configure --prefix=${HOME}/netcdf
+#          make -j2
+#          make install
+#
+#      # Get NetCDF versions
+#      - name: Get NetCDF version
+#        run: |
+#          export PATH="${HOME}/netcdf/bin:$PATH"
+#          nc-config --version
+#          nf-config --version
+#
+#      # Test debug mode
+#      - name: Test Shallow Water Debug
+#        run: |
+#          source /opt/intel/oneapi/setvars.sh
+#          export PATH="${HOME}/openmpi/bin:$PATH"
+#          ldd ${HOME}/openmpi/bin/mpicc
+#          ldd ${HOME}/openmpi/bin/mpif90
+#          ldd ${HOME}/netcdf/lib/libnetcdf
+#          cd build
+#          rm -rf *
+#          export CC=icc
+#          export FC=ifort
+#          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_PREFIX_PATH='~;~/netcdf;~/openmpi' ..
+#          make VERBOSE=1
+#          ctest --output-on-failure
+#
+#      # Test release mode
+#      - name: Test Shallow Water Release
+#        run: |
+#          source /opt/intel/oneapi/setvars.sh
+#          export PATH="${HOME}/openmpi/bin:$PATH"
+#          cd build
+#          rm -rf *
+#          export CC=mpicc
+#          export FC=mpif90
+#          cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_PREFIX_PATH='~;~/netcdf;~/openmpi' ..
+#          make VERBOSE=1
+#          ctest --output-on-failure
